### ISSUE TITLE
Multi-machine test is broken

### ISSUE THREAD

**Issue by 8enmann** [cybertronai/transformer-xl#7]
Steps to repro: start multi-machine run, ^C during training. After eval & load best checkpoint, it throws:
```
Traceback (most recent call last):
  File "train.py", line 745, in <module>
    main()
  File "train.py", line 729, in main
    model = torch.load(model_f, map_location=lambda storage, loc: storage.cuda(args.local_rank))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "train.py", line 745, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
  File "train.py", line 729, in main
    model = torch.load(model_f, map_location=lambda storage, loc: storage.cuda(args.local_rank))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input
```

**Comment by 8enmann** [comment]
No explanation?

**Comment by yaroslavvb** [comment]
Oh, is it still broken? I haven't seen this error in any of my testing

**Comment by 8enmann** [comment]
Have you tried Ctrl c with multiple machines?

**Comment by 8enmann** [comment]
Probably need to broadcast the interrupt signal

**Comment by yaroslavvb** [comment]
Just tried it with 2 machines and it didn't crash. But it didn't seem to evaluate things correctly either

<img width="821" alt="Screenshot 2019-05-05 18 42 49" src="https://user-images.githubusercontent.com/23068/57203544-dc4e2680-6f65-11e9-9d28-f0f9730fa306.png">
