### ISSUE TITLE
Figure out how to install pytorch 1.1 in new env on AWS

### ISSUE THREAD

**Issue by yaroslavvb** [cybertronai/transformer-xl#9]
Things tried

```
conda create --name=pytorch_11 --clone pytorch_p36
source activate pytorch_11
pip install torch==1.1.0
python -c "import torch"
```

On brand new machine
```
conda create --name=pytorch_11 --clone pytorch_p36
source activate pytorch_11
conda install pytorch torchvision -c pytorch
python -c "import torch"
```

Both fail with

```
Traceback (most recent call last):
  File "check_versions.py", line 12, in <module>
    import torch.optim as optim
  File "/home/ubuntu/anaconda3/envs/pytorch_11/lib/python3.6/site-packages/torch/__init__.py", line 222, in <module>
    class BoolStorage(_C.BoolStorageBase, _StorageBase):
AttributeError: module 'torch._C' has no attribute 'BoolStorageBase'
```
cc @8enmann 

Some kind of weird interaction with conda clone and new pytorch install 
https://github.com/pytorch/pytorch/issues/20403

**Comment by yaroslavvb** [comment]
Building from source worked.
It's now under env `pytorch_april_patched` in image `cybertronai01`
